# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=20, verbose_name='视频地址'),
        ),
    ]
