# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
