# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-10 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171031_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecode',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='验证码时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update', '修改邮箱')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
