# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_courseorg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='org/%Y/%m', verbose_name='封面图'),
        ),
    ]
