# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20171106_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='teacher/%Y/%m/', verbose_name='头像'),
        ),
    ]
