# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_dj',
            field=models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], default='gj', max_length=10, verbose_name='等级'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years',
            field=models.IntegerField(default=25, verbose_name='年龄'),
        ),
    ]
